// <auto-generated />
namespace RenderLogy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial2));
        
        string IMigrationMetadata.Id
        {
            get { return "201409220742022_initial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
